### ISSUE TITLE
"Content not provided" in webpages.

### ISSUE THREAD

**Issue by lightnin** [sabszh/EER-chatbot-UI#1]
The bot says it doesn't have access to the content on the EER website pages.
<img width="827" alt="Screenshot 2024-04-10 at 15 21 45" src="https://github.com/sabszh/EER-chatbot-UI/assets/1538027/88012312-e73a-43d1-ab67-1b955981a212">

**Comment by lightnin** [comment]
Hey @sabszh is this one fixed already?

**Comment by sabszh** [comment]
> Hey @sabszh is this one fixed already?

Yes. I think the issue was more in the prompting, as the data exists in the vector base.
I just tried prompting it differently, and it gave me a more in-depth answer 

![image](https://github.com/sabszh/EER-chatbot-UI/assets/87586469/6126f58b-eb59-4075-9784-1bdf95ee5709)

(Unsure about the formatting here, it usually occurs like that markdown style when there is code included)

**Comment by lightnin** [comment]
Seems good!
